name: Build, Push, and Deploy Docker Image for 2048

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u mosgarage --password-stdin

      - name: Build and push the Docker image
        run: |
          docker build . --tag ghcr.io/mosgarage/mosgarage-home:latest
          docker push ghcr.io/mosgarage/mosgarage-home:latest

  deploy:
    needs: build_and_publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u mosgarage --password-stdin

      - name: Pull Docker image
        run: docker pull ghcr.io/mosgarage/mosgarage-home:latest

      - name: Create a container and extract static files
        run: |
          mkdir -p ./public
          docker run --rm -d --name mosgarage-homer ghcr.io/mosgarage/mosgarage-home:latest
          sleep 10 # Wait for the container to start
          docker cp mosgarage-home:/var/www/html ./public
          docker stop mosgarage-home
          ls -la ./public # List files to ensure index.html is present

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./public/html  # Adjusted path to the html folder
          publish_branch: gh-pages
